services:
  tuya-to-mqtt:
    image: ghcr.io/tfoote000/eg4heatpumptuyatomqtt:latest
    # build: .  # uncomment to build from source instead
    env_file:
      - .env
    volumes:
      - ./devices.json:/app/devices.json:ro
    working_dir: /app
    restart: unless-stopped
    network_mode: host
